name: fiberchat #changing it will force you to change appname in import statement inside every .dart file.
description: Chats & Calling app

version: 2.0.10+80
publish_to: none

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  google_translate: 0.0.6
  logger: 1.4.0
  cloud_functions: 4.1.0
  audioplayers: 4.0.1
  pin_input_text_field: 4.2.0
  audio_session: 0.1.13
  flutter_cache_manager: 3.3.0
  rxdart: 0.27.5
  better_open_file: 3.6.4
  file_saver: 0.1.1
  gallery_saver: 2.3.2
  url_launcher: 6.1.3
  circular_countdown_timer: 0.2.1
  camera: 0.10.5
  oktoast: 3.3.1
  holding_gesture: 1.1.0
  flutter_emoji: 2.4.0
  pip_view: 0.9.6-nullsafety
  page_transition: 2.0.5
  wechat_assets_picker: 8.0.0
  image_editor: 1.0.2
  video_editor: 1.4.3
  flutter_image_compress: 1.1.0
  mime: 1.0.1
  video_compress: 3.1.2
  link_preview_generator: 1.2.0
  google_mobile_ads: 2.0.1
  font_awesome_flutter: 9.2.0
  sms_autofill: 2.2.0
  receive_sharing_intent: 1.4.5
  firebase_crashlytics: 3.0.3
  async: 2.10.0
  emoji_picker_flutter: 1.3.1
  flutter_video_info: 1.3.1
  group_button: 3.3.1
  flutter_colorpicker: 0.6.1
  devicelocale: 0.5.4
  http_auth: 1.0.1
  cloud_firestore: 4.7.0
  flutter_cached_pdfview: 0.4.1
  firebase_messaging: 14.1.4
  cached_network_image: 3.2.1
  firebase_storage: 11.0.3
  device_info_plus: 8.1.0
  file_picker: 5.2.2
  path_provider: 2.0.12
  path: 1.8.2
  flutter_sound: 9.2.13
  percent_indicator: 4.2.2
  string_validator: 0.3.0
  ntp: 2.0.0
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  intl: 0.17.0
  connectivity_plus: 3.0.3
  http: 0.13.5
  provider: 6.0.3
  firebase_auth: 4.1.0
  html: 0.15.0
  image_picker: 0.8.7+1
  universal_platform: 1.0.0+1
  flutter_linkify: 5.0.2
  dotted_border: 2.0.0+1
  diacritic: 0.1.3
  image_cropper: 1.5.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: 2.0.0-nullsafety.0
  local_auth: 2.1.2
  crypto: 3.0.2
  encrypt: 5.0.1
  localstorage: 4.0.0+1
  photo_view: 0.12.0
  launch_review: 3.0.1
  overlay_support: 2.0.1
  jiffy: 4.1.0
  geolocator: 7.7.1
  video_player: 2.4.5
  video_thumbnail: 0.5.3
  chewie: 1.3.4
  media_info: 0.8.0
  firebase_core: 2.12.0
  shared_preferences: 2.0.15
  permission_handler: 10.2.0
  agora_rtc_engine: 6.1.1+1
  flutter_local_notifications: 12.0.4
  flutter_secure_storage: 5.0.2
  package_info_plus: 3.0.3
  giphy_get: 3.1.0
  wakelock: 0.6.2
  cupertino_icons: 1.0.5
  collection: 1.17.0
  dropdown_plus: 0.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8

  flutter_launcher_icons: ^0.9.2
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
